### ISSUE TITLE
Compilation fails on OpenSUSE

### ISSUE THREAD

**Issue by hsanjuan** [atlas-engineer/cl-webengine#2]
Hello,

openSUSE names the QtWebEngine library `libQt5WebEngine.so` and therefore building this fails by default. This is fixed by updating `package.lisp` accordingly.

**Comment by jmercouris** [comment]
Thank you, for the report! Sorry I did not see this earlier, I forgot to watch the repository :-D

**Comment by jmercouris** [comment]
Just to clarify, `qmake` and then `make` produce a file called `libQt5WebEngine.so` on your distribution?

**Comment by hsanjuan** [comment]
I don't compile Qt myself. I mean that the rpm-provided pre-compiled library in openSUSE names it `libQt5WebEngine.so` not `libwebengine.so`.

**Comment by jmercouris** [comment]
I think there may be a small amount of confusion here, sorry about that!

In package.lisp, the following:

```
(define-foreign-library libwebengine
  (:darwin (:or
            "libwebengine.dylib"
            "libwebengine.1.dylib"
            "libwebengine.1.0.dylib"
            "libwebengine.1.0.0.dylib"))
  (:unix (:or "libwebengine.so"
              "libwebengine.so.1"
              "libwebengine.so.1.0"
              "libwebengine.so.1.0.0"))
  (t (:default "libwebengine")))

```

is not meant to load the Qt webengine. It is meant to load a shared library produced by compiling cl-webengine called libwebengine. In the source directory of this repository, if you type `qmake` and `make` you'll get the shared library which you can then copy into your shared library directory to be loaded by cl-webengine.

Sorry if the above description is a bit confusing, these bindings in general are confusing :-D

**Comment by hsanjuan** [comment]
oooh, ok, that explains some things. Sorry for this!

**Comment by jmercouris** [comment]
No problem at all :-)
